title: Solo Futbol Amateur
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Solo Futbol Amateur es un blog de futbol
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://solofutbolamateur.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

collections:
  - cien_equipos_campeones
  - ligas-de-futbol-nicolas-romero
  - escuelas-de-futbol-nicolas-romero

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
